version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - dataops_network

  postgres:
    image: postgres:15
    container_name: contenedor-procesado
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataops_network

  postgres_raw:
    image: postgres:15-alpine
    container_name: db_telemetria_cruda
    environment:
      POSTGRES_USER: ${DB_USER2}
      POSTGRES_PASSWORD: ${DB_PASSWORD2}
      POSTGRES_DB: ${DB_NAME2}
    ports:
      - "5433:5432"
    volumes:
      - pg_data_raw:/var/lib/postgresql/data
    networks:
      - dataops_network

  spark-streaming:
    build:
      context: ./data_pipeline
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - dataops_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-api:
    build:
      context: ./backend_api
    depends_on:
      - postgres
      - postgres_raw
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - dataops_network
    
  frontend-app:
    build:
      context: ./frontend_app
    depends_on:
      - backend-api
    ports:
      - "8501:8501"
    networks:
      - dataops_network
    command: streamlit run app_frontend.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false

  productor-iot:
    build:
      context: ./productor-iot
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - PYTHONBUFFERED=1
    networks:
      - dataops_network
    restart: always

volumes:
  postgres_data:
  pg_data_raw:

networks:
  dataops_network:
    driver: bridge