services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_broker
    restart: always
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - dataops_network

  postgres:
    image: postgres:15
    container_name: postgres_gold
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataops_network

  spark-streaming:
    container_name: spark_streaming
    build:
      context: ./data_pipeline
    depends_on:
      - kafka
      - postgres
      - minio # Agregado para asegurar que MinIO levante antes que Spark
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - DB_HOST=postgres
      - DB_PORT=5432
      - MINIO_ENDPOINT=http://minio:9000
      - PYTHONBUFFERED=1
    networks:
      - dataops_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-api:
    container_name: backend_api
    build:
      context: ./backend_api
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - dataops_network
    
  frontend-app:
    container_name: frontend_app
    build:
      context: ./frontend_app
    depends_on:
      - backend-api
    ports:
      - "8501:8501"
    networks:
      - dataops_network
    command: streamlit run app_frontend.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false

  productor-iot:
    container_name: productor_iot
    build:
      context: ./productor-iot
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - PYTHONUNBUFFERED=1
    networks:
      - dataops_network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio_datalake
    ports:
      - "9000:9000"   # Puerto para conexión de Spark (API S3)
      - "9001:9001"   # Puerto para la Interfaz Gráfica (Web UI)
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-admin}           # Homologado con tu .env
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-password123} # Homologado con tu .env
    volumes:
      - ./minio_data:/data              # Carpeta local para que no se borren los datos
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  pg_data_raw:

networks:
  dataops_network:
    driver: bridge