version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin_dataops
      POSTGRES_PASSWORD: password_seguro_123
      POSTGRES_DB: iot_predictivo
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark-streaming:
    build:
      context: ./data_pipeline
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - DB_HOST=postgres
      - DB_PORT=5432
    # Usamos la red interna de Docker para conectarnos a Kafka y Postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-api:
    build:
      context: ./backend_api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    
  frontend-app:
    build:
      context: ./frontend_app
    depends_on:
      - backend-api
    ports:
      - "8501:8501"

  productor-iot:
    build:
      context: ./productor-iot
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

volumes:
  postgres_data: